# This is a basic workflow to help you get started with Actions

name: API

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, dev, api-dev]
  pull_request:
    branches: [main, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "newman"
  newman:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          ls 
          cd api 
          ls
          npm install 
          npm run start
          mongod
      - uses: matt-ball/newman-action@v0.2.4
        with:
          collection: api/BoxOfHopeAPI.postman_collection.json
          environment: api/InitialTestEnvironment.postman_environment.json
